name: cosmoga
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - astropy
  - numdifftools
  - multiprocess
  - tqdm
  - corner
  - emcee
  - pip
  - pip:
      - pygad
